#!/usr/bin/env bash
# configures a server for Nginx to be running, and listen on port 80 for all the servers active IPv4 IPs

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
