#!/usr/bin/env bash
# configures a server for Nginx to be running, and listen on port 80 for all the server’s active IPv4 IPs(in short)
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
