#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd.
#   Your script should only display:
#       username
#       user id
#       Home directory path for the user

while read -r passwd
do
    echo "$passwd" | cut -d ':' -f 1,3,6
done < "/etc/passwd"
