#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, but "Hy" on ninth

i=1
until [ $i -eq 10 ];
do
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi;
    echo "Best School"
    (( i++ ));
done
