#!/usr/bin/env bash
# Install, setup a few rules, and configure ufw so that it blocks all incoming traffic,
# except the following TCP ports: 22 (SSH), 443 (HTTPS SSL), 80 (HTTP)

apt-get install ufw
sqd -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw enable
ufw default deny incoming
ufw default deny outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
