#!/usr/bin/env bash
# configures the container so that Nginx is running as the nginx user, nginx listens on all active IPs on port 8080 without using 'apt-get remove'
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
